#!/usr/bin/env python3
"""
AI Code Review Bot
Automatically reviews pull requests using Claude AI
"""

import os
import sys
from anthropic import Anthropic

def get_pr_diff():
    """Get the PR diff from the file created by GitHub Actions"""
    diff_file = 'pr_diff.txt'
    
    try:
        if os.path.exists(diff_file):
            with open(diff_file, 'r') as f:
                content = f.read()
                if not content or len(content.strip()) == 0:
                    print("ERROR: Diff file is empty")
                    return None
                return content
        else:
            print(f"ERROR: Diff file '{diff_file}' not found")
            return None
    except Exception as e:
        print(f"Error reading diff: {e}")
        return None

def review_code(diff):
    """Send code diff to Claude for review"""
    
    api_key = os.getenv('ANTHROPIC_API_KEY')
    if not api_key:
        print("ERROR: ANTHROPIC_API_KEY not found in environment variables")
        sys.exit(1)
    
    client = Anthropic(api_key=api_key)
    
    prompt = f"""You are an expert code reviewer. Review the following code changes and provide:

1. **Security Issues**: Any potential security vulnerabilities (SQL injection, XSS, authentication issues, etc.)
2. **Bug Risks**: Possible bugs or edge cases not handled (null checks, error handling, etc.)
3. **Code Quality**: Style issues, best practices, readability improvements
4. **Performance**: Any performance concerns or optimization opportunities
5. **Suggestions**: Specific improvements with code examples where helpful

Be constructive, specific, and reference line numbers or function names where applicable.
If the code looks good, acknowledge what was done well before suggesting improvements.

CODE DIFF:
```
{diff}
```

Provide your review in markdown format with clear sections."""

    try:
        response = client.messages.create(
            model="claude-sonnet-4-20250514",
            max_tokens=2000,
            messages=[
                {"role": "user", "content": prompt}
            ]
        )
        
        return response.content[0].text
    
    except Exception as e:
        print(f"Error calling Claude API: {e}")
        return None

def format_review_comment(review):
    """Format the review as a GitHub comment"""
    
    comment = f"""## 🤖 AI Code Review

{review}

---
*This review was automatically generated by Claude AI. Please use human judgment for final decisions.*
"""
    return comment

def save_review(comment):
    """Save review to file for GitHub Actions to post"""
    
    output_file = 'review_comment.md'
    
    try:
        with open(output_file, 'w') as f:
            f.write(comment)
        print(f"✅ Review saved to {output_file}")
        print("\n" + "="*60)
        print("REVIEW PREVIEW:")
        print("="*60)
        print(comment)
        return True
    except Exception as e:
        print(f"❌ Error saving review: {e}")
        return False

def main():
    print("🚀 Starting AI Code Review Bot...")
    
    # Step 1: Get PR diff
    print("\n📥 Fetching PR diff...")
    diff = get_pr_diff()
    
    if not diff:
        print("❌ Could not retrieve PR diff")
        sys.exit(1)
    
    print(f"✅ Retrieved diff ({len(diff)} characters)")
    
    # Step 2: Review code with Claude
    print("\n🔍 Analyzing code with Claude AI...")
    review = review_code(diff)
    
    if not review:
        print("❌ Code review failed")
        sys.exit(1)
    
    print("✅ Review generated")
    
    # Step 3: Format and save comment
    print("\n💬 Formatting review comment...")
    comment = format_review_comment(review)
    
    # Step 4: Save review
    print("\n📤 Saving review...")
    if save_review(comment):
        print("✅ Review saved successfully!")
    else:
        print("❌ Failed to save review")
        sys.exit(1)

if __name__ == "__main__":
    main()
