#!/usr/bin/env python3
"""
AI Code Review Bot
Automatically reviews pull requests using Claude AI
"""

import os
import sys
import json
from anthropic import Anthropic

def get_pr_diff():
    """Get the PR diff from GitHub Actions environment or file"""
    # In GitHub Actions, diff is passed via file
    diff_file = os.getenv('GITHUB_EVENT_PATH', 'pr_diff.txt')
    
    try:
        if os.path.exists(diff_file):
            with open(diff_file, 'r') as f:
                content = f.read()
                # If it's a GitHub event, extract diff
                try:
                    event = json.loads(content)
                    # This is simplified - in real use, fetch diff from PR
                    return event.get('pull_request', {}).get('body', content)
                except json.JSONDecodeError:
                    return content
        else:
            print("No diff file found. Using sample diff.")
            return """
diff --git a/app.py b/app.py
index 1234567..abcdefg 100644
--- a/app.py
+++ b/app.py
@@ -10,7 +10,7 @@ def calculate_total(items):
     total = 0
     for item in items:
-        total = total + item['price']
+        total += item['price']
     return total
"""
    except Exception as e:
        print(f"Error reading diff: {e}")
        return None

def review_code(diff):
    """Send code diff to Claude for review"""
    
    api_key = os.getenv('ANTHROPIC_API_KEY')
    if not api_key:
        print("ERROR: ANTHROPIC_API_KEY not found in environment variables")
        sys.exit(1)
    
    client = Anthropic(api_key=api_key)
    
    prompt = f"""You are an expert code reviewer. Review the following code changes and provide:

1. **Security Issues**: Any potential security vulnerabilities
2. **Bug Risks**: Possible bugs or edge cases not handled
3. **Code Quality**: Style issues, best practices, readability
4. **Performance**: Any performance concerns
5. **Suggestions**: Specific improvements with code examples

Be constructive and specific. If the code looks good, say so!

CODE DIFF:
{diff}

Provide your review in clear sections with specific line references where applicable."""

    try:
        response = client.messages.create(
            model="claude-sonnet-4-20250514",
            max_tokens=2000,
            messages=[
                {"role": "user", "content": prompt}
            ]
        )
        
        return response.content[0].text
    
    except Exception as e:
        print(f"Error calling Claude API: {e}")
        return None

def format_review_comment(review):
    """Format the review as a GitHub comment"""
    
    comment = f"""## 🤖 AI Code Review

{review}

---
*This review was automatically generated by Claude AI. Please use human judgment for final decisions.*
"""
    return comment

def post_comment_to_github(comment):
    """Post review comment to GitHub PR"""
    
    # In a real implementation, this would use GitHub API
    # For now, we'll just output to a file that GitHub Actions can use
    
    output_file = os.getenv('GITHUB_OUTPUT', 'review_comment.md')
    
    try:
        with open(output_file, 'w') as f:
            f.write(comment)
        print(f"Review saved to {output_file}")
        print("\n" + "="*60)
        print("REVIEW PREVIEW:")
        print("="*60)
        print(comment)
        return True
    except Exception as e:
        print(f"Error saving review: {e}")
        return False

def main():
    print("🚀 Starting AI Code Review Bot...")
    
    # Step 1: Get PR diff
    print("\n📥 Fetching PR diff...")
    diff = get_pr_diff()
    
    if not diff:
        print("❌ Could not retrieve PR diff")
        sys.exit(1)
    
    print(f"✅ Retrieved diff ({len(diff)} characters)")
    
    # Step 2: Review code with Claude
    print("\n🔍 Analyzing code with Claude AI...")
    review = review_code(diff)
    
    if not review:
        print("❌ Code review failed")
        sys.exit(1)
    
    print("✅ Review generated")
    
    # Step 3: Format and post comment
    print("\n💬 Formatting review comment...")
    comment = format_review_comment(review)
    
    # Step 4: Save/post comment
    print("\n📤 Posting review...")
    if post_comment_to_github(comment):
        print("✅ Review posted successfully!")
    else:
        print("❌ Failed to post review")
        sys.exit(1)

if __name__ == "__main__":
    main()
